**MY FIRST R PROGRAM**

In [5]:
print ("I love R Prog")

[1] "I love R Prog"

In [6]:
print ("I love R Prog")

cat ("R", "Prog")

[1] "I love R Prog"
R Prog

**Variables & Data Types**

In [8]:
myString <- "I love u"
wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE

print (myString)

class(myString)
class(wholeNum)
class(floatingNum)
class(isBool)

[1] "I love u"

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

**NUMERICAL OPERATOR**

In [9]:
x <- 10
y <- 3
z <- x + y

add <- x + y #Addition
sub <- x - y #Subtraction
mul <- x * y #Multiplication
div <- x / y #Division
mod <- x %% y #Modulus
mod <- x ^ y #Exponent


print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(exp)

print(z)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1000
function (x)  .Primitive("exp")
[1] 13

**USER INPUT**

In [11]:
name <- readline("Enter your name")

cat ("hello to the R prog: ", name)

Enter your namejean mickel baterbonia
hello to the R prog:  jean mickel baterbonia

**DECISION MAKING**

In [15]:
grade <- 80

if (grade < 75 ){
  print ("failed")
}else{
  print ("passed")
}

[1] "passed"

**LOOP**

In [18]:
for (i in 1:6){  print (i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6

**FUNCTIONS**

In [20]:
addNumber <- function(a,b){
  return(a+b)
}

addNumber(3,7)

[1] 10

**VECTORS**

In [25]:
grades <- c(99,80,98,97,95)

grades

cat("Mean: ",mean(grades))
cat("\nmax:",max(grades))
cat("\nMin: ",min(grades))
cat("\nlength:",length(grades))
cat("\nMedian: ",median(grades))

[1] 99 80 98 97 95

Mean:  93.8
max: 99
Min:  80
length: 5
Median:  97

**MATRICES**

In [28]:
A <- matrix(c(1,2,3,4,5,6),nrow=2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

**LIST**

In [31]:
students <- list(
  Name = "John Kurt",
  Course = "BSCS",
  Grade = 65
)

students

$Name
[1] "John Kurt"

$Course
[1] "BSCS"

$Grade
[1] 65

**DATA FRAME**

In [35]:
students <- data.frame(
  name = c("JK", "LABAHO", "HAHA"),
  course = c("BSCS", "BSIT", "BS Comp Vulca"),
  grade = c(94,96,99)
  )

  students

  name   course        grade
1 JK     BSCS          94
2 LABAHO BSIT          96
3 HAHA   BS Comp Vulca 99

**WRITE to CSV**

In [36]:
write.csv(students, "students.csv")

**READ CSV FILE**

In [39]:
data <- read.csv("students.csv")
head(data)
summary(data)

  X name   course        grade
1 1 JK     BSCS          94
2 2 LABAHO BSIT          96
3 3 HAHA   BS Comp Vulca 99

       X              name         course       grade
 Min.   :1.0   Length   :3   Length   : 3   Min.   :94.00
 1st Qu.:1.5   N.unique :3   N.unique : 3   1st Qu.:95.00
 Median :2.0   N.blank  :0   N.blank  : 0   Median :96.00
 Mean   :2.0   Min.nchar:2   Min.nchar: 4   Mean   :96.33
 3rd Qu.:2.5   Max.nchar:6   Max.nchar:13   3rd Qu.:97.50
 Max.   :3.0                                Max.   :99.00